config/routes.rb
UKDotaAppOfficial::Application.routes.draw do

  resources :matches

  resources :topics

  resources :chats

  resources :user_connections

  resources :users

   root to: "home#index"

  post 'auth/steam/callback' => 'welcome#auth_callback'

  get 'rss_feeds/' => 'rss_feeds#index'

  get 'teams/' => 'teams#index'

  

end

app/models/user_connection.rb
class UserConnection < ActiveRecord::Base
  attr_accessible :friend, :user_1_id, :user_2_id

  belongs_to :user_1, :class_name => :User
  belongs_to :user_2, :class_name => :User
end

app/controllers/user_connections_controller.rb
class UserConnectionsController < ApplicationController
  # GET /user_connections
  # GET /user_connections.json
  def index
    @user_connections = UserConnection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_connections }
    end
  end

  # GET /user_connections/1
  # GET /user_connections/1.json
  def show
    @user_connection = UserConnection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_connection }
    end
  end

  # GET /user_connections/new
  # GET /user_connections/new.json
  def new
    @user_connection = UserConnection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_connection }
    end
  end

  # GET /user_connections/1/edit
  def edit
    @user_connection = UserConnection.find(params[:id])
  end

  # POST /user_connections
  # POST /user_connections.json
  def create
    @user_connection = UserConnection.new(params[:user_connection])
    
    respond_to do |format|
      if @user_connection.save
        format.html { redirect_to @user_connection, notice: 'User connection was successfully created.' }
        format.json { render json: @user_connection, status: :created, location: @user_connection }
      else
        format.html { render action: "new" }
        format.json { render json: @user_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_connections/1
  # PUT /user_connections/1.json
  def update
    
    @user_connection = UserConnection.find(params[:id])

    respond_to do |format|
      if @user_connection.update_attributes(params[:user_connection])
        format.html { redirect_to @user_connection, notice: 'User connection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_connections/1
  # DELETE /user_connections/1.json
  def destroy
    @user_connection = UserConnection.find(params[:id])
    @user_connection.destroy

    respond_to do |format|
      format.html { redirect_to user_connections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_connections_helper.rb
module UserConnectionsHelper
end

app/views/user_connections/_form.html.erb
<%= form_for(@user_connection) do |f| %>
  <% if @user_connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_connection.errors.count, "error") %> prohibited this user_connection from being saved:</h2>

      <ul>
      <% @user_connection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :friend %><br />
    <%= f.check_box :friend %>
  </div>
  <div class="field">
    <%= f.label :user_1_id %><br />
    <%= f.number_field :user_1_id %>
  </div>
  <div class="field">
    <%= f.label :user_2_id %><br />
    <%= f.number_field :user_2_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_connections/edit.html.erb
<h1>Editing user_connection</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_connection %> |
<%= link_to 'Back', user_connections_path %>

app/views/user_connections/index.html.erb
<h1>Listing user_connections</h1>

<table>
  <tr>
    <th>Friend</th>
    <th>User 1</th>
    <th>User 2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_connections.each do |user_connection| %>
  <tr>
    <td><%= user_connection.friend %></td>
    <td><%= user_connection.user_1_id %></td>
    <td><%= user_connection.user_2_id %></td>
    <td><%= link_to 'Show', user_connection %></td>
    <td><%= link_to 'Edit', edit_user_connection_path(user_connection) %></td>
    <td><%= link_to 'Destroy', user_connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User connection', new_user_connection_path %>

app/views/user_connections/new.html.erb
<h1>New user_connection</h1>

<%= render 'form' %>

<%= link_to 'Back', user_connections_path %>

app/views/user_connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Friend:</b>
  <%= @user_connection.friend %>
</p>

<p>
  <b>User 1:</b>
  <%= @user_connection.user_1_id %>
</p>

<p>
  <b>User 2:</b>
  <%= @user_connection.user_2_id %>
</p>


<%= link_to 'Edit', edit_user_connection_path(@user_connection) %> |
<%= link_to 'Back', user_connections_path %>