config/routes.rb
UKDotaAppOfficial::Application.routes.draw do

  resources :matches

  resources :topics

  resources :chats

  resources :user_connections

  resources :users

   root to: "home#index"

  post 'auth/steam/callback' => 'welcome#auth_callback'

  get 'rss_feeds/' => 'rss_feeds#index'

  get 'teams/' => 'teams#index'

  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :created_by, :description, :title, :user_id

  belongs_to :user
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all(:order => 'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = current_user.id
    @topic.created_by = current_user.steam_nickname
    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div id='forum_title'>
<img class='forum_inline' src="../images/uk_dota_logo.jpeg" height='100px'>
<h1 id='forum_title'  class='forum_inline'>Welcome to the UK Dota forum!</h1>
<img class='forum_inline' src="../images/uk_dota_logo.jpeg" height='100px'>
</div>

  <h3 id='new_topic_link'><%= link_to 'New Topic', new_topic_path %></h3>

<div id='topics'>
  <% @topics.each do |topic| %>
    
      <div id='each_topic'>
     <h2><%= topic.title %></h2>
     <p><%= topic.description %></p>
     <p>Created by: <%=topic.created_by %> <p>
     <%= link_to 'Show', topic %><br>
      <!-- <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </div>
    <br>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Description:</b>
  <%= @topic.description %>
</p>

<p>
  <b>Created by:</b>
  <%= @topic.created_by %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>