config/routes.rb
UKDotaAppOfficial::Application.routes.draw do

  resources :matches

  resources :topics

  resources :chats

  resources :user_connections

  resources :users

   root to: "home#index"

  post 'auth/steam/callback' => 'welcome#auth_callback'

  get 'rss_feeds/' => 'rss_feeds#index'

  get 'teams/' => 'teams#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :steam_id, :steam_image, :steam_nickname, :matchlist

  has_many(:user_connections, :foreign_key => :user_1_id, :dependent => :destroy)
  has_many(:reverse_user_connections, :class_name => :UserConnection, :foreign_key => :user_2_id, :dependent => :destroy)
  has_many :users, :through => :user_connections, :source => :user_2

  has_many(:chats, :foreign_key => :user_1_id, :dependent => :destroy)
  has_many(:reverse_chats, :class_name => :Chat, :foreign_key => :user_2_id, :dependent => :destroy)
  has_many :users, :through => :chats, :source => :user_2

  has_many :topics

  has_many :matches

  def self.find_for_steam_oauth(auth, signed_in_user=nil)

    if  User.find_by_steam_nickname(auth.info.nickname)
      
      User.find_by_steam_nickname(auth.info.nickname)
   
    else 
      user = User.new
      user.steam_id = auth.uid.to_i
      user.steam_nickname = auth.info.nickname
      user.steam_image = auth.info.image
      user.save
      user
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @q = User.search(params[:q])
    @users = @q.result(distinct: true)



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    @matchlist = []
    if session.key? :current_user
      url = URI.parse("https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v001/?key=#{ENV['STEAM_WEB_API_KEY']}&account_id=#{session[:current_user][:uid]}")
      res = Net::HTTP::get(url)
      @matchlist = JSON.load(res)['result']['matches'] || []
    end
   
    Match.save_match_from_matchlist(@matchlist, current_user) 
   
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :steam_nickname %><br />
    <%= f.text_field :steam_nickname %>
  </div>
  <div class="field">
    <%= f.label :steam_id %><br />
    <%= f.number_field :steam_id %>
  </div>
  <div class="field">
    <%= f.label :steam_image %><br />
    <%= f.text_field :steam_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div id='users_search_page'>
<h1>Listing users</h1>

<%= search_form_for @q do |f| %>
<p>
  <%= f.label :steam_nickname %>
  <%= f.text_field :steam_nickname_cont %>
  <%= f.submit %>
</p>

<% end %>

<table>
 

<% @users.each do |user| %>
  <tr>
    <td><img src="<%= user.steam_image %>"></td>
    <td><a href="/users/<%= user.id %>"><%= user.steam_nickname %></a></td>
  </tr>
<% end %>
</table>

<br />
<div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div id='profile_nav_buttons'>
<% if @user.id == current_user.id %>
    <button id='show_profile'>Profile</button>  <button id='show_friends_list'>Friends</button>
  <%end%>
</div>
<div id='profile_page'>
  
  <div id='general_info'>
    <p class='general_info_specifics'>
      <%= image_tag @user.steam_image %>
    </p>
    <p class='general_info_specifics'>
      <b>Steam name:</b>
      <%= @user.steam_nickname %>
    </p>
    <p class='general_info_specifics'>
      <b>Steam Id:</b>
      <%= @user.steam_id %>
    </p>
    <div class='general_info_specifics'>
    <% if @user.id != current_user.id %>
    <button id='add_friend'>Add to friends</button>
    <button><%= link_to "Send message", chats_path(:id => @user.id, :name => @user.steam_nickname), :id => "chat" %></button>
    <%end%>

    <% if @user.id == current_user.id %>
      <%= link_to 'Edit Profile', edit_user_path(@user) %> 
    <% end %>
    </div>
    <select id="hidden_current_user_id">
      <option><%= current_user.id %></option>
    </select>
    <select id="hidden_user_id">
      <option><%= @user.id %></option>
    </select>
  </div>

  <div id='match_history'>
    <h2> Ten most recent matches </h2>
    <ul>
      <% @user.matches.first(10).map do |match| %>
      <li><a href="http://www.dotabuff.com/matches/<%= match.steam_id %>">Match</a></li>
      <% end %>
    </ul>
  </div> 

  
</div>
<% if @user.id == current_user.id %>
<div id='friends_list'>
<h1>Friends List!</h1>
<ul id='friends_list_names'>
<% if current_user.user_connections %>
<% current_user.user_connections.each do |user| %>
  <% user %>
  <li><a href="/users/<%= user.user_2_id %>"><%= User.find(user.user_2_id).steam_nickname %></a></li><br>
 
<% end %>
<% end %>
</ul>
<%end%>

<%= @user.matchlist %>

</div>